### ISSUE TITLE
按照swiper@^11.1.14引入样式会报错

### ISSUE THREAD

**Issue by 0fan** [huangmingfu/react-ts-template#1]
如图,页面能够显示,但是ts会报错
![image](https://github.com/user-attachments/assets/501bcd48-4625-4139-ae89-1567c53dbe7e)
这是swiper的package.json,貌似是exports没解析对
![image](https://github.com/user-attachments/assets/a2f97fab-b309-4024-8e91-8af7ae469950)

**Comment by huangmingfu** [comment]
类型错误解决：
在global.d.ts定义如下，示例：
declare module 'swiper/css';
declare module 'swiper/scss';
declare module 'swiper/scss/navigation';
declare module 'swiper/scss/pagination';

嫌麻烦一个个定义可以直接这样一行搞定：
declare module 'swiper/*';

只是类型报错误而已，实际上是有引入到的
![image](https://github.com/user-attachments/assets/537932e0-3bd9-4700-870f-2b6d9771d2c3)
